name: ApiClient
output: /src/client
url: http://localhost:8000/api-json
generateClient: true
generateRouteTypes: true
generateResponses: true
toJS: false
extractRequestParams: true
extractRequestBody: true
prettier:
  printWidth: 120
  tabWidth: 2
  trailingComma: all
  parser: typescript
defaultResponseAsSuccess: false
singleHttpClient: true
cleanOutput: true
enumNamesAsValues: false
moduleNameFirstTag: true
generateUnionEnums: true
extraTemplates: [] 